# Generated by Django 4.2.7 on 2023-11-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel_image_path_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('visit', 'Visit'), ('draft_booking', 'Draft Booking'), ('completed_booking', 'Completed Booking')], max_length=20),
        ),
    ]
